version: '3.8'

services:
  client:
    build: ./mine_sweeper_client
    image: ms_cli_img
    container_name: ms_cli_cont
    # dev only
    volumes:
      - ./mine_sweeper_client/src:/client/src
      - /client/node_modules
    ports:
      - 5173:5173
    depends_on:
      - server

  server:
    build: ./mine_sweeper_server
    image: ms_ser_img
    container_name: ms_ser_cont
    env_file:
      - '.env'
    # dev only
    volumes:
      - ./mine_sweeper_server/server:/server/server
      - /server/node_modules
    ports:
      - 4000:4000
    depends_on:
      pg_db:
        condition: service_healthy

  pg_db:
    image: postgres:latest
    container_name: ms_pg_cont
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
